'use strict';
console.log("Hello world!");
console.log("دنیا سلام!");
console.log("مرحبا بالعالم!");
console.log("Привет мир!");
console.log("Olá Mundo!");
console.log("こんにちは世界!");
console.log("silav dinya!");
console.log("Ahoj světe!");
console.log("สวัสดีชาวโลก!");
console.log("Γειά σου Κόσμε!");
